export const INPUT_NUMBER = 'INPUT_NUMBER';
export const INPUT_OPERATOR = 'INPUT_OPERATOR';
export const INPUT_ADVANCED_OPERATOR = 'INPUT_ADVANCED_OPERATOR';
export const EVALUATE_EXPRESSION = 'EVALUATE_EXPRESSION';
export const CLEAR_LAST_INPUT = 'CLEAR_LAST_INPUT';
export const CLEAR_EXPRESSION = 'CLEAR_EXPRESSION';
export const RESET_CLEAR = 'RESET_CLEAR';
export const RESET_ERROR = 'RESET_ERROR';
